//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace NFSE.Net.Tests.NFse.Net.Consulta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultarNEPorRpsBinding", Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class ConsultarNEPorRpsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarNfsePorRpsEnvioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarNfseRpsEnvioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultarNEPorRpsService() {
            this.Url = global::NFSE.Net.Tests.Properties.Settings.Default.NFSE_Net_Tests_NFse_Net_Consulta_ConsultarNEPorRpsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarNfsePorRpsEnvioCompletedEventHandler ConsultarNfsePorRpsEnvioCompleted;
        
        /// <remarks/>
        public event ConsultarNfseRpsEnvioCompletedEventHandler ConsultarNfseRpsEnvioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultarNfsePorRpsEnvioResponse", Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
        public ConsultarNfsePorRpsEnvioResponse ConsultarNfsePorRpsEnvio([System.Xml.Serialization.XmlElementAttribute("ConsultarNfsePorRpsEnvio", Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")] ConsultarNfsePorRpsEnvio ConsultarNfsePorRpsEnvio1) {
            object[] results = this.Invoke("ConsultarNfsePorRpsEnvio", new object[] {
                        ConsultarNfsePorRpsEnvio1});
            return ((ConsultarNfsePorRpsEnvioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarNfsePorRpsEnvioAsync(ConsultarNfsePorRpsEnvio ConsultarNfsePorRpsEnvio1) {
            this.ConsultarNfsePorRpsEnvioAsync(ConsultarNfsePorRpsEnvio1, null);
        }
        
        /// <remarks/>
        public void ConsultarNfsePorRpsEnvioAsync(ConsultarNfsePorRpsEnvio ConsultarNfsePorRpsEnvio1, object userState) {
            if ((this.ConsultarNfsePorRpsEnvioOperationCompleted == null)) {
                this.ConsultarNfsePorRpsEnvioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarNfsePorRpsEnvioOperationCompleted);
            }
            this.InvokeAsync("ConsultarNfsePorRpsEnvio", new object[] {
                        ConsultarNfsePorRpsEnvio1}, this.ConsultarNfsePorRpsEnvioOperationCompleted, userState);
        }
        
        private void OnConsultarNfsePorRpsEnvioOperationCompleted(object arg) {
            if ((this.ConsultarNfsePorRpsEnvioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarNfsePorRpsEnvioCompleted(this, new ConsultarNfsePorRpsEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultarNfseRpsEnvioResponse", Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
        public ConsultarNfseRpsEnvioResponse ConsultarNfseRpsEnvio([System.Xml.Serialization.XmlElementAttribute("ConsultarNfseRpsEnvio", Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")] ConsultarNfseRpsEnvio ConsultarNfseRpsEnvio1) {
            object[] results = this.Invoke("ConsultarNfseRpsEnvio", new object[] {
                        ConsultarNfseRpsEnvio1});
            return ((ConsultarNfseRpsEnvioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarNfseRpsEnvioAsync(ConsultarNfseRpsEnvio ConsultarNfseRpsEnvio1) {
            this.ConsultarNfseRpsEnvioAsync(ConsultarNfseRpsEnvio1, null);
        }
        
        /// <remarks/>
        public void ConsultarNfseRpsEnvioAsync(ConsultarNfseRpsEnvio ConsultarNfseRpsEnvio1, object userState) {
            if ((this.ConsultarNfseRpsEnvioOperationCompleted == null)) {
                this.ConsultarNfseRpsEnvioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarNfseRpsEnvioOperationCompleted);
            }
            this.InvokeAsync("ConsultarNfseRpsEnvio", new object[] {
                        ConsultarNfseRpsEnvio1}, this.ConsultarNfseRpsEnvioOperationCompleted, userState);
        }
        
        private void OnConsultarNfseRpsEnvioOperationCompleted(object arg) {
            if ((this.ConsultarNfseRpsEnvioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarNfseRpsEnvioCompleted(this, new ConsultarNfseRpsEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class ConsultarNfsePorRpsEnvio {
        
        private tcIdentificacaoRps identificacaoRpsField;
        
        private tcIdentificacaoPrestador prestadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoRps IdentificacaoRps {
            get {
                return this.identificacaoRpsField;
            }
            set {
                this.identificacaoRpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoPrestador Prestador {
            get {
                return this.prestadorField;
            }
            set {
                this.prestadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoRps {
        
        private string numeroField;
        
        private string serieField;
        
        private int tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class ConsultarNfseRpsEnvioResponse {
        
        private consultarNfseRpsResposta consultarNfseRpsRespostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public consultarNfseRpsResposta ConsultarNfseRpsResposta {
            get {
                return this.consultarNfseRpsRespostaField;
            }
            set {
                this.consultarNfseRpsRespostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class consultarNfseRpsResposta {
        
        private tcCompNfse complNfseField;
        
        private tcMensagemRetorno[] listaMensagemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcCompNfse ComplNfse {
            get {
                return this.complNfseField;
            }
            set {
                this.complNfseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public tcMensagemRetorno[] ListaMensagemRetorno {
            get {
                return this.listaMensagemRetornoField;
            }
            set {
                this.listaMensagemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcCompNfse {
        
        private tcNfse nfseField;
        
        private tcCancelamentoNfse nfseCancelamentoField;
        
        private tcSubstituicaoNfse nfseSubstituicaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcNfse Nfse {
            get {
                return this.nfseField;
            }
            set {
                this.nfseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcCancelamentoNfse NfseCancelamento {
            get {
                return this.nfseCancelamentoField;
            }
            set {
                this.nfseCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcSubstituicaoNfse NfseSubstituicao {
            get {
                return this.nfseSubstituicaoField;
            }
            set {
                this.nfseSubstituicaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcNfse {
        
        private tcInfNfse infNfseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcInfNfse InfNfse {
            get {
                return this.infNfseField;
            }
            set {
                this.infNfseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcInfNfse {
        
        private string numeroField;
        
        private string codigoVerificacaoField;
        
        private System.DateTime dataEmissaoField;
        
        private tcIdentificacaoRps identificacaoRpsField;
        
        private System.DateTime dataEmissaoRpsField;
        
        private bool dataEmissaoRpsFieldSpecified;
        
        private int naturezaOperacaoField;
        
        private int regimeEspecialTributacaoField;
        
        private bool regimeEspecialTributacaoFieldSpecified;
        
        private int optanteSimplesNacionalField;
        
        private int incentivadorCulturalField;
        
        private System.DateTime competenciaField;
        
        private string nfseSubstitutaField;
        
        private string outrasInformacoesField;
        
        private tcDadosServico servicoField;
        
        private decimal valorCreditoField;
        
        private bool valorCreditoFieldSpecified;
        
        private tcDadosPrestador prestadorServicoField;
        
        private tcDadosTomador tomadorServicoField;
        
        private tcIdentificacaoIntermediarioServico intermediarioServicoField;
        
        private tcIdentificacaoOrgaoGerador orgaoGeradorField;
        
        private tcDadosConstrucaoCivil construcaoCivilField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoVerificacao {
            get {
                return this.codigoVerificacaoField;
            }
            set {
                this.codigoVerificacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DataEmissao {
            get {
                return this.dataEmissaoField;
            }
            set {
                this.dataEmissaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoRps IdentificacaoRps {
            get {
                return this.identificacaoRpsField;
            }
            set {
                this.identificacaoRpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DataEmissaoRps {
            get {
                return this.dataEmissaoRpsField;
            }
            set {
                this.dataEmissaoRpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataEmissaoRpsSpecified {
            get {
                return this.dataEmissaoRpsFieldSpecified;
            }
            set {
                this.dataEmissaoRpsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NaturezaOperacao {
            get {
                return this.naturezaOperacaoField;
            }
            set {
                this.naturezaOperacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RegimeEspecialTributacao {
            get {
                return this.regimeEspecialTributacaoField;
            }
            set {
                this.regimeEspecialTributacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegimeEspecialTributacaoSpecified {
            get {
                return this.regimeEspecialTributacaoFieldSpecified;
            }
            set {
                this.regimeEspecialTributacaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int OptanteSimplesNacional {
            get {
                return this.optanteSimplesNacionalField;
            }
            set {
                this.optanteSimplesNacionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IncentivadorCultural {
            get {
                return this.incentivadorCulturalField;
            }
            set {
                this.incentivadorCulturalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime Competencia {
            get {
                return this.competenciaField;
            }
            set {
                this.competenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NfseSubstituta {
            get {
                return this.nfseSubstitutaField;
            }
            set {
                this.nfseSubstitutaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutrasInformacoes {
            get {
                return this.outrasInformacoesField;
            }
            set {
                this.outrasInformacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcDadosServico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorCredito {
            get {
                return this.valorCreditoField;
            }
            set {
                this.valorCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCreditoSpecified {
            get {
                return this.valorCreditoFieldSpecified;
            }
            set {
                this.valorCreditoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcDadosPrestador PrestadorServico {
            get {
                return this.prestadorServicoField;
            }
            set {
                this.prestadorServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcDadosTomador TomadorServico {
            get {
                return this.tomadorServicoField;
            }
            set {
                this.tomadorServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoIntermediarioServico IntermediarioServico {
            get {
                return this.intermediarioServicoField;
            }
            set {
                this.intermediarioServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoOrgaoGerador OrgaoGerador {
            get {
                return this.orgaoGeradorField;
            }
            set {
                this.orgaoGeradorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcDadosConstrucaoCivil ConstrucaoCivil {
            get {
                return this.construcaoCivilField;
            }
            set {
                this.construcaoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcDadosServico {
        
        private tcValores valoresField;
        
        private string itemListaServicoField;
        
        private int codigoCnaeField;
        
        private bool codigoCnaeFieldSpecified;
        
        private string codigoTributacaoMunicipioField;
        
        private string discriminacaoField;
        
        private int codigoMunicipioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcValores Valores {
            get {
                return this.valoresField;
            }
            set {
                this.valoresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemListaServico {
            get {
                return this.itemListaServicoField;
            }
            set {
                this.itemListaServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CodigoCnae {
            get {
                return this.codigoCnaeField;
            }
            set {
                this.codigoCnaeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoCnaeSpecified {
            get {
                return this.codigoCnaeFieldSpecified;
            }
            set {
                this.codigoCnaeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoTributacaoMunicipio {
            get {
                return this.codigoTributacaoMunicipioField;
            }
            set {
                this.codigoTributacaoMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Discriminacao {
            get {
                return this.discriminacaoField;
            }
            set {
                this.discriminacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcValores {
        
        private decimal valorServicosField;
        
        private decimal valorDeducoesField;
        
        private bool valorDeducoesFieldSpecified;
        
        private decimal valorPisField;
        
        private bool valorPisFieldSpecified;
        
        private decimal valorCofinsField;
        
        private bool valorCofinsFieldSpecified;
        
        private decimal valorInssField;
        
        private bool valorInssFieldSpecified;
        
        private decimal valorIrField;
        
        private bool valorIrFieldSpecified;
        
        private decimal valorCsllField;
        
        private bool valorCsllFieldSpecified;
        
        private int issRetidoField;
        
        private bool issRetidoFieldSpecified;
        
        private decimal valorIssField;
        
        private bool valorIssFieldSpecified;
        
        private decimal outrasRetencoesField;
        
        private bool outrasRetencoesFieldSpecified;
        
        private decimal baseCalculoField;
        
        private decimal aliquotaField;
        
        private bool aliquotaFieldSpecified;
        
        private decimal valorLiquidoNfseField;
        
        private bool valorLiquidoNfseFieldSpecified;
        
        private decimal valorIssRetidoField;
        
        private bool valorIssRetidoFieldSpecified;
        
        private decimal descontoCondicionadoField;
        
        private bool descontoCondicionadoFieldSpecified;
        
        private decimal descontoIncondicionadoField;
        
        private bool descontoIncondicionadoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorServicos {
            get {
                return this.valorServicosField;
            }
            set {
                this.valorServicosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorDeducoes {
            get {
                return this.valorDeducoesField;
            }
            set {
                this.valorDeducoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorDeducoesSpecified {
            get {
                return this.valorDeducoesFieldSpecified;
            }
            set {
                this.valorDeducoesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorPis {
            get {
                return this.valorPisField;
            }
            set {
                this.valorPisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorPisSpecified {
            get {
                return this.valorPisFieldSpecified;
            }
            set {
                this.valorPisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorCofins {
            get {
                return this.valorCofinsField;
            }
            set {
                this.valorCofinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCofinsSpecified {
            get {
                return this.valorCofinsFieldSpecified;
            }
            set {
                this.valorCofinsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorInss {
            get {
                return this.valorInssField;
            }
            set {
                this.valorInssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorInssSpecified {
            get {
                return this.valorInssFieldSpecified;
            }
            set {
                this.valorInssFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorIr {
            get {
                return this.valorIrField;
            }
            set {
                this.valorIrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIrSpecified {
            get {
                return this.valorIrFieldSpecified;
            }
            set {
                this.valorIrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorCsll {
            get {
                return this.valorCsllField;
            }
            set {
                this.valorCsllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorCsllSpecified {
            get {
                return this.valorCsllFieldSpecified;
            }
            set {
                this.valorCsllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IssRetido {
            get {
                return this.issRetidoField;
            }
            set {
                this.issRetidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssRetidoSpecified {
            get {
                return this.issRetidoFieldSpecified;
            }
            set {
                this.issRetidoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorIss {
            get {
                return this.valorIssField;
            }
            set {
                this.valorIssField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIssSpecified {
            get {
                return this.valorIssFieldSpecified;
            }
            set {
                this.valorIssFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal OutrasRetencoes {
            get {
                return this.outrasRetencoesField;
            }
            set {
                this.outrasRetencoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutrasRetencoesSpecified {
            get {
                return this.outrasRetencoesFieldSpecified;
            }
            set {
                this.outrasRetencoesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BaseCalculo {
            get {
                return this.baseCalculoField;
            }
            set {
                this.baseCalculoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Aliquota {
            get {
                return this.aliquotaField;
            }
            set {
                this.aliquotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AliquotaSpecified {
            get {
                return this.aliquotaFieldSpecified;
            }
            set {
                this.aliquotaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorLiquidoNfse {
            get {
                return this.valorLiquidoNfseField;
            }
            set {
                this.valorLiquidoNfseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorLiquidoNfseSpecified {
            get {
                return this.valorLiquidoNfseFieldSpecified;
            }
            set {
                this.valorLiquidoNfseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ValorIssRetido {
            get {
                return this.valorIssRetidoField;
            }
            set {
                this.valorIssRetidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorIssRetidoSpecified {
            get {
                return this.valorIssRetidoFieldSpecified;
            }
            set {
                this.valorIssRetidoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DescontoCondicionado {
            get {
                return this.descontoCondicionadoField;
            }
            set {
                this.descontoCondicionadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescontoCondicionadoSpecified {
            get {
                return this.descontoCondicionadoFieldSpecified;
            }
            set {
                this.descontoCondicionadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DescontoIncondicionado {
            get {
                return this.descontoIncondicionadoField;
            }
            set {
                this.descontoIncondicionadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescontoIncondicionadoSpecified {
            get {
                return this.descontoIncondicionadoFieldSpecified;
            }
            set {
                this.descontoIncondicionadoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcDadosPrestador {
        
        private tcIdentificacaoPrestador identificacaoPrestadorField;
        
        private string razaoSocialField;
        
        private string nomeFantasiaField;
        
        private tcEndereco enderecoField;
        
        private tcContato contatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoPrestador IdentificacaoPrestador {
            get {
                return this.identificacaoPrestadorField;
            }
            set {
                this.identificacaoPrestadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomeFantasia {
            get {
                return this.nomeFantasiaField;
            }
            set {
                this.nomeFantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcEndereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcContato Contato {
            get {
                return this.contatoField;
            }
            set {
                this.contatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoPrestador {
        
        private string cnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcEndereco {
        
        private string enderecoField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private int codigoMunicipioField;
        
        private bool codigoMunicipioFieldSpecified;
        
        private string ufField;
        
        private int cepField;
        
        private bool cepFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodigoMunicipioSpecified {
            get {
                return this.codigoMunicipioFieldSpecified;
            }
            set {
                this.codigoMunicipioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CepSpecified {
            get {
                return this.cepFieldSpecified;
            }
            set {
                this.cepFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcContato {
        
        private string telefoneField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcDadosTomador {
        
        private tcIdentificacaoTomador identificacaoTomadorField;
        
        private string razaoSocialField;
        
        private tcEndereco enderecoField;
        
        private tcContato contatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoTomador IdentificacaoTomador {
            get {
                return this.identificacaoTomadorField;
            }
            set {
                this.identificacaoTomadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcEndereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcContato Contato {
            get {
                return this.contatoField;
            }
            set {
                this.contatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoTomador {
        
        private tcCpfCnpj cpfCnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcCpfCnpj CpfCnpj {
            get {
                return this.cpfCnpjField;
            }
            set {
                this.cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcCpfCnpj {
        
        private string cnpjField;
        
        private string cpfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoIntermediarioServico {
        
        private string razaoSocialField;
        
        private tcCpfCnpj cpfCnpjField;
        
        private string inscricaoMunicipalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcCpfCnpj CpfCnpj {
            get {
                return this.cpfCnpjField;
            }
            set {
                this.cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoOrgaoGerador {
        
        private int codigoMunicipioField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcDadosConstrucaoCivil {
        
        private string codigoObraField;
        
        private string artField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoObra {
            get {
                return this.codigoObraField;
            }
            set {
                this.codigoObraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcCancelamentoNfse {
        
        private tcConfirmacaoCancelamento confirmacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcConfirmacaoCancelamento Confirmacao {
            get {
                return this.confirmacaoField;
            }
            set {
                this.confirmacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcConfirmacaoCancelamento {
        
        private tcPedidoCancelamento pedidoField;
        
        private tcInfConfirmacaoCancelamento infConfirmacaoCancelamentoField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcPedidoCancelamento Pedido {
            get {
                return this.pedidoField;
            }
            set {
                this.pedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcInfConfirmacaoCancelamento InfConfirmacaoCancelamento {
            get {
                return this.infConfirmacaoCancelamentoField;
            }
            set {
                this.infConfirmacaoCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcPedidoCancelamento {
        
        private tcInfPedidoCancelamento infPedidoCancelamentoField;
        
        private Signature signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcInfPedidoCancelamento InfPedidoCancelamento {
            get {
                return this.infPedidoCancelamentoField;
            }
            set {
                this.infPedidoCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public Signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcInfPedidoCancelamento {
        
        private tcIdentificacaoNfse identificacaoNfseField;
        
        private string codigoCancelamentoField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoNfse IdentificacaoNfse {
            get {
                return this.identificacaoNfseField;
            }
            set {
                this.identificacaoNfseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoCancelamento {
            get {
                return this.codigoCancelamentoField;
            }
            set {
                this.codigoCancelamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcIdentificacaoNfse {
        
        private string numeroField;
        
        private string cnpjField;
        
        private string inscricaoMunicipalField;
        
        private string codigoMunicipioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InscricaoMunicipal {
            get {
                return this.inscricaoMunicipalField;
            }
            set {
                this.inscricaoMunicipalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Signature {
        
        private tcSigInfo signedInfoField;
        
        private string signatureValueField;
        
        private tcKeyInfo keyInfoField;
        
        /// <remarks/>
        public tcSigInfo SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        public string SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public tcKeyInfo KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcSigInfo {
        
        private tcCanonicalizationMethod canonicalizationMethodField;
        
        private tcSignatureMethod signatureMethodField;
        
        private tcReference referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public tcCanonicalizationMethod CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public tcSignatureMethod SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public tcReference Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcCanonicalizationMethod {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcSignatureMethod {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcReference {
        
        private tcTransform[] transformsField;
        
        private tcDigestMethod digestMethodField;
        
        private string digestValueField;
        
        private string uRIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public tcTransform[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public tcDigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public string DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcTransform {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcDigestMethod {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcKeyInfo {
        
        private tcX509Data x509DataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public tcX509Data X509Data {
            get {
                return this.x509DataField;
            }
            set {
                this.x509DataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class tcX509Data {
        
        private string x509CertificateField;
        
        /// <remarks/>
        public string X509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcInfConfirmacaoCancelamento {
        
        private bool sucessoField;
        
        private System.DateTime dataHoraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcSubstituicaoNfse {
        
        private tcInfSubstituicaoNfse substituicaoNfseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcInfSubstituicaoNfse SubstituicaoNfse {
            get {
                return this.substituicaoNfseField;
            }
            set {
                this.substituicaoNfseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcInfSubstituicaoNfse {
        
        private string nfseSubstituidoraField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NfseSubstituidora {
            get {
                return this.nfseSubstituidoraField;
            }
            set {
                this.nfseSubstituidoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class tcMensagemRetorno {
        
        private string codigoField;
        
        private string mensagemField;
        
        private string correcaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Correcao {
            get {
                return this.correcaoField;
            }
            set {
                this.correcaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class ConsultarNfseRpsEnvio {
        
        private tcIdentificacaoRps identificacaoRpsField;
        
        private tcIdentificacaoPrestador prestadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoRps IdentificacaoRps {
            get {
                return this.identificacaoRpsField;
            }
            set {
                this.identificacaoRpsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tcIdentificacaoPrestador Prestador {
            get {
                return this.prestadorField;
            }
            set {
                this.prestadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.betha.com.br/e-nota-contribuinte-ws")]
    public partial class ConsultarNfsePorRpsEnvioResponse {
        
        private consultarNfseRpsResposta consultarNfseRpsRespostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public consultarNfseRpsResposta ConsultarNfseRpsResposta {
            get {
                return this.consultarNfseRpsRespostaField;
            }
            set {
                this.consultarNfseRpsRespostaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarNfsePorRpsEnvioCompletedEventHandler(object sender, ConsultarNfsePorRpsEnvioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfsePorRpsEnvioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarNfsePorRpsEnvioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarNfsePorRpsEnvioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarNfsePorRpsEnvioResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarNfseRpsEnvioCompletedEventHandler(object sender, ConsultarNfseRpsEnvioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseRpsEnvioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarNfseRpsEnvioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarNfseRpsEnvioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarNfseRpsEnvioResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591